# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Travis continuous integration system configuration file.
#
# Overview on how to customize the configuration is located at:
# http://docs.travis-ci.com/user/customizing-the-build/

# Sudo-enabled Ubuntu Trusty environment. https://docs.travis-ci.com/user/trusty-ci-environment/
sudo: required
dist: trusty

# Use Node.js as primary language because Gulp is the build system used in the project.
language: node_js

# Cache downloaded Node.JS modules & Bower frontend dependencies for faster builds.
cache:
  directories:
    - node_modules
    - bower_components
    - .tools



before_script:
  # Install go 1.7.1. It is not there by default.
  - eval "$(gimme 1.7.1)"
  - docker --version

script:
  - ./build/install_cluster.sh
