version: "1.0"

name: kubernetes-dashboard

services:
  web:
    build:
      context: ..
      dockerfile: modules/web/Dockerfile
      args:
        - BUILDPLATFORM=linux/amd64
    command:
      --locale-config /public/locale_conf.json
      --auto-generate-certificates
    ports:
      - "8001:8001"
  api:
    build:
      context: ..
      dockerfile: modules/api/Dockerfile
      args:
        - BUILDPLATFORM=linux/amd64
    command:
      --kubeconfig ${HOME}/.kube/config
      --auto-generate-certificates
    volumes:
      - ${HOME}/.kube:${HOME}/.kube
    ports:
      - "9000:9000"
  gateway:
    build:
      context: ../
      dockerfile: hack/gateway/Dockerfile
    ports:
      - "4443:4443"

networks:
  kubernetes-dashboard:
    name: kubernetes-dashboard
