# Copyright 2017 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: CD
on:
  push:
    branches: [master]
  pull_request:
    branches: [ master ] # TODO: Remove before merging.
  create:
    tags:
      - "v*.*.*"
permissions:
  contents: read
  packages: write
env:
  GOPATH: /home/runner/go/
  GOPROXY: "https://proxy.golang.org"
  NG_CLI_ANALYTICS: ci
  NODE_OPTIONS: "--max-old-space-size=8192"
  TERM: xterm
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: modules/api/go.mod
          check-latest: true
          cache-dependency-path: modules/api/go.sum
      - uses: actions/setup-node@v4
        with:
          node-version: 18.14.0
      - working-directory: modules/web
        run: yarn

      - uses: docker/setup-qemu-action@v3.0.0
      - uses: docker/setup-buildx-action@v3.0.0
      - uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_RELEASE_USER }}
          password: ${{ secrets.DOCKER_RELEASE_PASS }}
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: github.event_name == 'push' && contains(github.ref, 'master')
        run: PATH=$PATH:$GOPATH/bin make deploy-dev
      - if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
        run: PATH=$PATH:$GOPATH/bin make deploy
